sudo: false
dist: xenial
language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2021-01-20
      env:
        - CARGO_INCREMENTAL=0
        - RUSTFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        - RUSTDOCFLAGS='-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

install:
- rustup component add rustfmt clippy
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then ./.travis/install-grcov.sh; fi

script:
- cargo build --all-features --verbose
- cargo test --all-features --verbose
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then ./.travis/coverage.sh; fi
- cargo clippy -- -Dwarnings
- cargo clippy --tests -- -Dwarnings
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then cargo fmt --all -- --check; fi
- cargo doc --no-deps

after_success:
- if [[ "$TRAVIS_RUST_VERSION" = nightly* ]]; then bash <(curl -s https://codecov.io/bash) -f lcov.info; fi
